### ISSUE TITLE
Can't push

### ISSUE THREAD

**Issue by samdoolin** [purplecat7/redsquirrel#2]
Do the repo permissions look ok?

```
Push failed
Failed with error: AggregateException encountered.
unable to access 'https://github.com/purplecat7/redsquirrel.git/': The requested URL returned error: 403
```

**Comment by purplecat7** [comment]
Hi Sam,

According to the collaborators list  for the repo, it's still awaiting a response to the invitation... I guess if that's missing then you're not deemed to have shaken hands on the deal :)

This is the link it gives me in case you've lost the mail...
https://github.com/purplecat7/redsquirrel/invitations

cheerio
Jane

J Lewis, Systems Engineer
Assimila Ltd, Reading Enterprise Centre
The University of Reading, RG6 6BU
Tel: +44 (0)118 935 7338
LIn: janetrishlewis

________________________________

**Comment by samdoolin** [comment]
Thank you! 

Didn't get the invitation - strange.
