### ISSUE TITLE
Time running out...

### ISSUE THREAD

**Issue by purplecat7** [purplecat7/redsquirrel#3]
Please everyone, submit skeleton code for the parts of the library system which you agreed to do on day1 of our OO course. We will be implementing at least one scenario this Friday and it'll be a bit tricky of there's nothing to work on!

**Comment by nparley** [comment]
Is there a list of who is doing what for the people who have forgotten

**Comment by purplecat7** [comment]
Luckily I did write it down!!! Although I think everyone had a piece of paper from the CRC work too.
Neil: ItemCollection, ItemManager (for setup)
SamD: UserCollection, UserManager (for setup)
Ben & SamB: Item, Book, DVD, Journal
Freja: User
Andy: LibraryController

**Comment by purplecat7** [comment]
Done
